version: "3"

services:
   app:
      container_name: agricultural
      build: .
      volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules
      depends_on:
         - mongo_db
      restart: always
      ports:
         - "5000:5000"
      environment:
         - DB_URL=mongodb://agricultural_mongo:2

   mongo_db:
      image: mongo:latest
      container_name: agricultural_mongo
      restart: always
      ports:
         - "27017:27017"
      volumes:
         - mongodata:/data/db

volumes:
   mongodata:
